app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Addon AI

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
  reading:
    allow:
      - host: 'raw.githubusercontent.com'

auth:
  providers:
    guest: {}
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

integrations:
  github:
    - host: github.com
      token: ${AUTH_GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

#catalog:
#  import:
#    entityFilename: catalog-info.yaml
#    pullRequestBranchName: backstage-integration
#  rules:
#    - allow: [Component, System, API, Resource, Location]
#  locations:
    # Local example data
#    - type: file
#      target: ../../examples/entities.yaml

    # Local example template
 #   - type: file
 #     target: ../../examples/template/template.yaml
 #     rules:
 #       - allow: [Template]

    # Local example organizational data
#    - type: file
#      target: ../../examples/org.yaml
#      rules:
#        - allow: [User, Group]

catalog:
  orphanStrategy: delete
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group, Domain]
  locations:
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: ../../examples/template/template.yaml
      rules:
       - allow: [Template]
    - type: url
      target: https://raw.githubusercontent.com/addon-ai/backstage-templates/refs/heads/main/back-ms-movies-webflux/template.yml
      rules:
       - allow: [Template]
  providers:
    github:
      addonAI:
        organization: 'addon-ai' # string
        catalogPath: '/*-location.yml' # string
        filters:
          branch: 'main'
        schedule:
          frequency: { minutes: 120 }
          timeout: { minutes: 3 }
      # personalAccount: #Cuenta Personal
      #  organization: 'Jiliar' # string
      #  catalogPath: '/catalog-info.yaml' # string
      #  filters: # optional filters
      #    branch: 'main' # optional string
      #    allowForks: false # optional boolean
      #    topic:
      #      include:
      #        - 'backstage-include'
      #  schedule:
      #    frequency: { minutes: 120 }
      #    timeout: { minutes: 3 }


kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

notifications:
  processors:
    email:
      transportConfig:
        transport: smtp
        hostname: ${EMAIL_SMTP_HOST}
        port: ${EMAIL_SMTP_PORT}
        secure: ${EMAIL_SMTP_SECURE}
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
      sender: ${EMAIL_SENDER}
      replyTo: ${EMAIL_REPLY_TO}
