#!/bin/bash
echo "Verificando catálogo de Backstage..."
echo ""
echo "1. Abre tu navegador en: http://localhost:3000"
echo "2. Haz login como Guest"
echo "3. Ve a: http://localhost:3000/catalog?filters[kind]=user"
echo "4. Busca el usuario 'jiliar-silgado'"
echo ""
echo "Si NO aparece, ejecuta:"
echo "  pkill -9 -f backstage-cli && yarn start"
echo ""
echo "Si SÍ aparece pero el login de Google falla:"
echo "  - Verifica que el email en Google sea: jiliar.silgado@gmail.com"
echo "  - Mira los logs del backend cuando hagas login"
