#!/bin/bash
echo "Verificando usuario en el catálogo..."
echo ""
echo "Haz lo siguiente:"
echo "1. Ve a http://localhost:3000"
echo "2. Login como Guest"
echo "3. Ve al Catalog > Users"
echo "4. Click en el usuario 'Jiliar'"
echo "5. Verifica que en el perfil aparezca: email: jiliar.silgado@gmail.com"
echo ""
echo "Si el email NO aparece o es diferente, el catálogo no se ha actualizado."
echo "Si el email SÍ aparece correcto, entonces el problema es otro."
echo ""
echo "Después, intenta login con Google y copia los logs que aparezcan aquí."
